# https://taskfile.dev

version: "3"

interval: 100ms

vars:
  NAME: "webui"
  BIN_NAME: "{{.NAME}}_bin"

tasks:
  libpub:
    dir: ./library
    cmds:
      - npm publish --access public
      - git push origin --tags

  library:
    dir: ./library
    generates:
      - "../{{.NAME}}/static/datastar*"
    sources:
      - "src/**/*.ts"
      - "package.json"
    cmds:
      - pnpm i
      # - pnpm vitest --watch=false
      - pnpm vite build
      - cp -Rfpvd dist/* ../{{.NAME}}/static
      - cp package.json ../{{.NAME}}/static

  tailwind:
    dir: ./{{.NAME}}/assetgen/css
    generates:
      - "../../static/tailwind.css"
    sources:
      - "../../**/*.go"
      - "tailwind.config.js"
    cmds:
      - pnpm i
      - pnpm tailwindcss -o ../../static/tailwind.css --minify

  frontend:
    deps:
      - tailwind
      - library

  kill:
    cmds:
      - killall -q {{.BIN_NAME}}  || echo "Process was not running."

  hot:
    desc: Server hot reload

    sources:
      - "**/*.go"
      - "webui/static/**/*"
      - "{{.NAME}}/static/**/*"
    deps:
      - kill
      - frontend

    cmds:
      - go mod tidy
      - go build -o ./{{.BIN_NAME}} cmd/{{.NAME}}/main.go
      - ./{{.BIN_NAME}}

  gen:
    dir: gen/{{.NAME}}
    cmds:
      - wget --mirror http://localhost:1337

  deploy:
    cmds:
      - fly deploy --local-only

  default:
    deps:
      - hot
    silent: false
