# https://taskfile.dev

version: "3"

interval: 100ms

vars:
  NAME: "docs"
  BIN_NAME: "{{.NAME}}_bin"

tasks:
  library:
    dir: ./library
    generates:
      - "../docs/static/datastar*"
    sources:
      - "src/**/*.ts"
      - "package.json"
    cmds:
      - pnpm i
      - pnpm vite build
      - cp -Rfpvd dist/* ../docs/static
      - cp package.json ../docs/static

  tailwind:
    dir: ./docs/assetgen/css
    generates:
      - "../../static/tailwind.css"
    sources:
      - "../../**/*.go"
      - "tailwind.config.js"
    cmds:
      - pnpm i
      - pnpm tailwindcss -o ../../static/tailwind.css

  frontend:
    deps:
      - tailwind
      - library

  kill:
    cmds:
      - killall -q {{.BIN_NAME}}  || echo "Process was not running."

  hot:
    desc: Server hot reload

    sources:
      - "**/*.go"
      # - "**/*.sql"
      - "docs/static/**/*"
    deps:
      - kill
      - frontend

    cmds:
      - go mod tidy
      - go build -o ./{{.BIN_NAME}} cmd/{{.NAME}}/main.go
      - ./{{.BIN_NAME}}

  gen:
    dir: gen/docs
    cmds:
      - wget --mirror http://localhost:1337

  default:
    deps:
      - hot
    silent: false
