name: Deploy Site
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  keyword_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Check for keyword in commit message
        id: check_keyword
        run: |
          if [[ "$(git log -1 --pretty=%B)" == *"deploy-site"* ]]; then
            echo "Keyword found"
            echo "run_action=true" >> $GITHUB_ENV
          else
            echo "No keyword found"
            echo "run_action=false" >> $GITHUB_ENV
          fi
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    needs: keyword_check
    if: ${{ env.run_action == 'true' }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          docker container run --rm -t -v "${{ github.workspace }}":/app -v go-modules:/go/pkg/mod ghcr.io/starfederation/datastar-dev -c 'task tools'
          docker container run --rm -t -v "${{ github.workspace }}":/app -v go-modules:/go/pkg/mod ghcr.io/starfederation/datastar-dev -c 'task support'
          flyctl deploy --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
