name: Fly Deploy
on:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/fly-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      # Bind the Docker socket for "Docker in Docker" as per: https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/
      - run: |
          docker container run --rm -t -v "${{ github.workspace }}":/app -v go-modules:/go/pkg/mod ghcr.io/starfederation/datastar-dev -c 'git lfs fetch --all && git lfs pull && git lfs checkout'
          docker container run --rm -t -v "${{ github.workspace }}":/app -v go-modules:/go/pkg/mod ghcr.io/starfederation/datastar-dev -c 'task tools'
          docker container run --rm -t -v "${{ github.workspace }}":/app -v go-modules:/go/pkg/mod -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/starfederation/datastar-dev -c 'task deploy'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
